import { useState } from "react"
import { AppSidebar } from "@/components/app-sidebar"
import { SiteHeader } from "@/components/site-header"
import { SectionCards } from "@/components/section-cards"
import { ChartAreaInteractive } from "@/components/chart-area-interactive"
import { DataTable } from "@/components/data-table"
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar"
import { useAuth } from "@/lib/auth-context"
import { EnvironmentManager } from "@/components/EnvironmentManager"

// The dummy data generated by shadcn for the DataTable
import dashboardData from "@/app/dashboard/data.json"

export function Dashboard() {
  const { profile, logout } = useAuth()
  const [activeView, setActiveView] = useState("Dashboard")
  
  return (
    <SidebarProvider>
      <AppSidebar 
        onLogout={logout} 
        user={{ name: profile?.username || "Guest", email: profile?.profile_type === "guest" ? "No Email" : "Local Encrypted", avatar: "" }} 
        activeView={activeView}
        onViewChange={setActiveView}
      />
      <SidebarInset>
        <SiteHeader />
        {activeView === "Environment Manager" ? (
          <EnvironmentManager />
        ) : (
          <div className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6">
            <SectionCards />
            <div className="grid grid-cols-1 gap-4 lg:grid-cols-3 lg:gap-6">
              <div className="lg:col-span-2">
                <ChartAreaInteractive />
              </div>
              <div>
                {/* Optional smaller component here if desired, or let data table take full width below */}
              </div>
            </div>
            <DataTable data={dashboardData} />
          </div>
        )}
      </SidebarInset>
    </SidebarProvider>
  )
}

